group 'com.gstory.flutter_unionad'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs project(':flutter_unionad').file('libs')
        }
        maven {
            url 'https://artifact.bytedance.com/repository/pangle'
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = "com.gstory.flutter_unionad"
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 16
        consumerProguardFiles 'proguard-rules.pro'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.appcompat:appcompat:1.3.1"

    implementation(name: 'open_ad_sdk_6.9.1.5', ext: 'aar')

    //ks
    implementation(name: "mediation_ks_adapter_3.3.76.5.1", ext: 'aar')
    implementation(name: "kssdk-ad-3.3.76.5", ext: 'aar')

    //baidu
    implementation(name: "mediation_baidu_adapter_9.3905.2", ext: 'aar')
    implementation(name: "Baidu_MobAds_SDK_v9.3905", ext: 'aar')

    //gdt
    implementation(name: "mediation_gdt_adapter_4.640.1510.1", ext: 'aar')
    implementation(name: "GDTSDK.unionNormal.4.640.1510", ext: 'aar')

}
